// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnemjqqjwqaecbtipran.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZW1qcXFqd3FhZWNidGlwcmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDk4OTksImV4cCI6MjA2NTcyNTg5OX0.BuOiNCdrqprUGNJ3m5h5GdK3c6F7_X-yYedRgfwJQJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);